#!/bin/sh
#
# Wrapper script to run Makeneutsmpl.csh when your PATH/LD_LIBRARY_PATH variables are too long for csh to handle.
#
LD_LIBRARY_PATH="$ROOTSYS/lib/root:${ROOTSYS}/lib" PATH="/bin:/usr/bin:$CERN/$CERN_LEVEL/bin:$ROOTSYS/bin" ./Makeneutsmpl.csh || exit 1

