#!/bin/sh
# Hack in crude Linux distribution detection to resolve some Linux
# Slackware vs. Debian issues
#
# This isn't guarenteed to work, since it's conceivable that /var/lib/dpkg 
# could exist on another system, but if the system is Debian then
# /var/lib/dpkg must exist.

OS=`uname`

if [ ${OS} != Linux ]; then
   exit 1
fi

if [ -f /etc/debian_version ]; then
   # Looks like we've got debian...
   case `cat /etc/debian_version` in
   1.3|bo)      VERSION=130;;
   2.0|hamm)    VERSION=200;;
   2.1|slink)   VERSION=210;;
   2.2|potato)  VERSION=220;;
   2.3|woody) VERSION=230;;
   2.4|*testing*|*unstable*) VERSION=240;;
   *) VERSION=999;;
   esac
   echo "-DDEBIAN=${VERSION}"
   exit 0
fi

if [ -f "/etc/redhat-release" ] ; then
    echo "-DREDHAT"
    exit 0
fi

if [ -d "/usr/lib/setup" ]; then
    case `ls /usr/lib/setup/slack-version*` in
    slack-version-4*)   VERSION=400;;
    slack-version-3*)   VERSION=300;;
    *)                  VERSION=200;;
    esac;
    echo "-DSLACKWARE=${VERSION}"
    exit 0
fi

exit 0
