*********************************************************
*                                                       *
* This file was generated by HUWFUN.                    *
*                                                       *
*    For flux up to 04a                                 *
*                                                       *
*********************************************************
*
*     Ntuple Id:      3001 
*     Ntuple Title:   Near Detector
*     Creation:       23/05/03 14.49.05
*
*********************************************************
*
      REAL EnuFD,ppiFD,xpiFD,npiFD,cospibmFD,normFD,ppi0FD,
     $     xpi0FD,npi0FD,cospi0bmFD,rFD,xnuFD,
     +     ynuFD,nnuFD
      INTEGER ppidFD,modeFD,idFD
      COMMON /FXVCND/ EnuFD,ppidFD,modeFD,ppiFD,xpiFD(3),npiFD(3),
     $                cospibmFD,normFD,ppi0FD,
     +                xpi0FD(3),npi0FD(3),cospi0bmFD,rFD,xnuFD,
     $                ynuFD,nnuFD(3),idFD

*********************************************************
*
*     Ntuple Id:      3000 
*     Ntuple Title:   Near Detector Setting
*     Creation:       23/05/03 14.49.05
*
*********************************************************
*
      REAL BXFD,BYFD,XFD,YFD,ZFD,HFD,VFD
      INTEGER NFD
      COMMON /NDDET/ NFD,BXFD(10),BYFD(10),XFD(10),YFD(10),ZFD(10)
     + ,HFD(10),VFD(10)

*********************************************************
*
*     Ntuple Id:      2000 
*     Ntuple Title:   nu at SK
*     Creation:       28/11/2007 01.15.44
*
*********************************************************
*
      REAL enusk,ppisk,xpisk(3),npisk(3),cospibmsk,normsk,
     +     ppi0sk,xpi0sk(3),npi0sk(3),cospi0bmsk
      INTEGER ppidsk,modesk
*
      COMMON /FXVCSK/ enusk,ppidsk,modesk,ppisk,xpisk,npisk,
     +                cospibmsk,normsk,ppi0sk,xpi0sk,npi0sk,
     +                cospi0bmsk
