## Check default NEUT_ROOT directory
ifndef NEUT_ROOT
      NEUT_ROOT = ../../
endif

include ${NEUT_ROOT}/src/neutsmpl/config_neut.gmk

LIBBASE	= skmcsvc
LIBNAME = ${LIBBASE}_$(SKMCSVCVER)

## For library
OBJS = fourVector.o calcLH.o selectSfValues.o buildSf.o maxDiff.o \
	   readXsecData.o sfevent.o selectEffSFValues.o effsfevent.o  \
	   buildEffSf.o effSFMaxDiff.o readEffSFXsecData.o

SOBJS = ${CLASSDIR}/neutctrl.so ${CLASSDIR}/neutpart.so \
		${CLASSDIR}/neutvect.so ${CLASSDIR}/neutvtx.so \
		${CLASSDIR}/neutnucfsistep.so \
		${CLASSDIR}/neutnucfsivert.so

ROBJS = ${CLASSDIR}/neutfill.o \
		${CLASSDIR}/neutrootfortwrapper.o \
		${CLASSDIR}/NeutRootHandlers.o 

OBJS  = ${ROBJS} ${SOBJS} 

.SUFFIXES:	.so

all: $(OBJS)

