      INTEGER NUCRESCAT,NUCRESFLG

          REAL*4  XNUCFACT
	  REAL*4  XNUCELAFACT
          REAL*4  XNUCSPIFACT
          REAL*4  XNUCDPIFACT

	COMMON /NUCRES/NUCRESCAT,XNUCFACT,XNUCELAFACT,XNUCSPIFACT,XNUCDPIFACT,NUCRESFLG

