*******************************************
*       COMMON BLOCK FOR FNELSPAU
*
*
*******************************************

      REAL CRSRFGLE(12,210)
      REAL CRSRFGRE(12,210)
      REAL CRSRFGLM(12,210)
      REAL CRSRFGRM(12,210)
      REAL CRSRFGLT(12,210)
      REAL CRSRFGRT(12,210)

      REAL CRSSFLE(12,210)
      REAL CRSSFRE(12,210)
      REAL CRSSFLM(12,210)
      REAL CRSSFRM(12,210)
      REAL CRSSFLT(12,210)
      REAL CRSSFRT(12,210)

      COMMON /QECRS/
     $       CRSRFGLE,CRSRFGRE,CRSRFGLM,CRSRFGRM,CRSRFGLT,CRSRFGRT,
     $       CRSSFLE,CRSSFRE,CRSSFLM,CRSSFRM,CRSSFLT,CRSSFRT
